# Generated by Django 5.1.4 on 2024-12-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSources',
            fields=[
                ('soure_id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('source_type', models.CharField(max_length=50)),
            ],
        ),
    ]
