# Generated by Django 5.1.4 on 2025-01-01 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConvertData', '0002_alter_datasources_soure_id_dataentries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataSources',
            new_name='DataSource',
        ),
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('FN', 'Finished'), ('ER', 'ERROR')], default='PD', max_length=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConvertData.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='NormalizeData',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('product', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(blank=None)),
                ('price', models.IntegerField(blank=None)),
                ('entry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConvertData.dataentry')),
            ],
        ),
        migrations.DeleteModel(
            name='DataEntries',
        ),
    ]
