# Generated by Django 5.1.4 on 2025-01-01 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConvertData', '0003_rename_datasources_datasource_dataentry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataentry',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='normalizedata',
            name='entry_id',
        ),
        migrations.DeleteModel(
            name='DataSource',
        ),
        migrations.DeleteModel(
            name='DataEntry',
        ),
        migrations.DeleteModel(
            name='NormalizeData',
        ),
    ]
